### ISSUE TITLE
Your package in npm is broken because of the symbol link

### ISSUE THREAD

**Issue by aristotll** [oprogramador/deep-equal-in-any-order#1]

**Comment by oprogramador** [comment]
Could you provide more details (your OS, NodeJS version, npm version, `deep-equal-in-any-order` version)?
Do you have problems when installing this library as a dependency or when developing it (`git clone`, `npm i`...)?

I checked `npm i --save deep-equal-in-any-order` works and `require('deep-equal-in-any-order')` returns a function.

**Comment by aristotll** [comment]
Of course it will work in your computer because your computer have the origin of the softlink...
I use mac os, by the way.

<img width="326" alt="2018-01-23 13 37 18" src="https://user-images.githubusercontent.com/13341544/35259791-b28e7798-0042-11e8-9a9c-40cfca34651b.png">

**Comment by oprogramador** [comment]
the symlink should be created in `postinstall` script so it should work on each machine (at least Unix-like)

but you're right it's broken

I'll fix that

**Comment by oprogramador** [comment]
it's fixed in 1.0.3 version

however this library is still work in progress
