### ISSUE TITLE
FEATURE - Work with chai-as-promised

### ISSUE THREAD

**Issue by fankohr** [oprogramador/deep-equal-in-any-order#23]
Hi !
This would be great if this lib could also work with chai-as-promised :)
I'm currently working on a TypeScript project and needed to have deep equals without order we're working a lot with promises so we use chai-as-promised for nearly every single tests.
For example 
`configService.updateConfiguration(data).should.be.fulfilled.and.eventually.have.property("config").to.deep.equalInAnyOrder(expectedData).notify(done);`

throw a TS error : `Property 'equalInAnyOrder' does not exist on type 'PromisedDeep'`

Thanks ! :)

**Comment by oprogramador** [comment]
Theoretically it should work.
I guess it's not a problem with connecting with `chai-as-promised` but rather missing TS typing.

Btw. instead of `chai-as-promised` you can use `async/await`.

**Comment by oprogramador** [comment]
@fankohr 

does it work for you?

**Comment by fankohr** [comment]
Hi !
We were in a bit of a rush so we decided to simply use `eql` and match the object order, i will try to find some time to make a pull request :)

**Comment by oprogramador** [comment]
so I close this because I don't maintain @types/deep-equal-in-any-order
