### ISSUE TITLE
Deep comparison with dates can fail

### ISSUE THREAD

**Issue by FranceJ** [oprogramador/deep-equal-in-any-order#35]
When comparing arrays of objects where some values in the objects are dates can result in a failed comparison. In particular, even if the dates are different deepEqualInAnyOrder will report that the objects are the same. 

Here is an example from runkit: 

https://runkit.com/embed/udx9x7ubw5xd

The deepEqualInAnyOrder passes but the have.deep.members assertion fails (which is the correct thing to do)

**Comment by oprogramador** [comment]
thanks,
I'll take a look when I find some time

**Comment by oprogramador** [comment]
@FranceJ @kf6kjg 

This issue is fixed in the `1.1.13` version.
