### ISSUE TITLE
Type definition broken w/ Chai

### ISSUE THREAD

**Issue by kataik** [oprogramador/deep-equal-in-any-order#38]
I get the following error when using the package latest from TypeScript / node v10 during tsc:

`node_modules/@types/deep-equal-in-any-order/index.d.ts:15:41 - error TS2694: Namespace 'Chai' has no exported member 'ChaiPlugin'.`

My (relevant) packages:
`
    "@types/chai": "^4.1.7",
    "@types/chai-as-promised": "^7.1.0",
    "@types/deep-equal-in-any-order": "^1.0.1",
    "@types/sinon": "^7.5.1",
    "@types/sinon-chai": "^3.2.2",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "deep-equal-in-any-order": "^1.0.21",
    "mocha": "^3.2.0",
    "sinon": "^8.0.1",
    "sinon-chai": "^3.4.0",
`

Can someone please help me? :)

**Comment by oprogramador** [comment]
it seems this file (another repo) https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/deep-equal-in-any-order/index.d.ts misses something, maybe there should be `namespace ChaiPlugin` inside `namespace Chai`

**Comment by oprogramador** [comment]
I close this because I don't maintain `@types/deep-equal-in-any-order`.
