### ISSUE TITLE
Support for assert?

### ISSUE THREAD

**Issue by alxndrsn** [oprogramador/deep-equal-in-any-order#69]
Thanks for the really useful little lib!

Does this lib currently support `chai.assert`?  If so, I can't work out how to use it.  If not, would you be open to a PR?  I'd be happy to provide.  I guess it would need:

* implementation of `assert.deepEqualInAnyOrder()`
* usage documentation for Assert in addition to the existing Expect docs

**Comment by oprogramador** [comment]
Hi @alxndrsn ,

thanks for your interest. I think theoretically, it should work with `chai.assert`, in a similar way as other chai plugins work but I have never checked that because I always use `expect`.

I'm open for PRs.

**Comment by oprogramador** [comment]
@alxndrsn 

Can we close this issue?

**Comment by alxndrsn** [comment]
@oprogramador thanks!
