### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by tomerghelber-tm** [oprogramador/deep-equal-in-any-order#72]
Hello,

The current version prints an error of:
`expected { Object (...) } to deeply equal { Object (...) }`

This is not so good to know what is wrong with the object we want to check.
Can a better error be created? preferred to have only the diff printed.

**Comment by oprogramador** [comment]
Could you check how it works with a pure `deep.equal`?

As I remember, `chai` may display something like that even without this plugin.
