### ISSUE TITLE
Compliance: no license

### ISSUE THREAD

**Issue by lucasgonze** [oprogramador/deep-equal-in-any-order#76]
The repo has no LICENSE file and does not declare a license in any other way. Therefore it is all-rights-reserved, not open source.

**Comment by oprogramador** [comment]
The license is specified here https://github.com/oprogramador/deep-equal-in-any-order/blob/a520180917cd2aad0b260f66f09f452940e8bcfd/package.json#L28

**Comment by lucasgonze** [comment]
There are two ways to apply the MIT license.

1. Put the text into a header in each source code file
2. Copy the standard template into a file named LICENSE at the top of your repo.

I have created a pull request to implement method 2:
https://github.com/oprogramador/deep-equal-in-any-order/pull/77

**Comment by oprogramador** [comment]
A license file is added in the `deep-equal-in-any-order@2.0.3` version.

**Comment by lucasgonze** [comment]
Thank you, @oprogramador !
