### ISSUE TITLE
semantic-release installed as dependency (should be devDep?)

### ISSUE THREAD

**Issue by AviVahl** [oprogramador/deep-equal-in-any-order#78]
I've noticed `npm` got installed in our `node_modules` due to this package depending on `semantic-release`.
Would you consider moving it to `devDependencies`, so it won't be installed for consumers?

Thanks for the package. Much appreciated.

**Comment by oprogramador** [comment]
Thanks for reporting.

It was straightforward but I was very busy. It's resolved in `deep-equal-in-any-order@2.0.5`
