### ISSUE TITLE
SUGGESTION: Locally defined types

### ISSUE THREAD

**Issue by kf6kjg** [oprogramador/deep-equal-in-any-order#83]
@oprogramador would you be open to either one of the following ideas?

- A PR adding the types to this package by adding a file at `src/index.d.ts` that defines the types exported by the index file? Would be very much like the file at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/deep-equal-in-any-order with some improvements, many of which would come from the closed tickets to this repo.
- A PR porting this package to Typescript?  We could talk about going to ESM and Chai v5 too.

In either case the `@types` package would also get a breaking change PR once the above was released marking the deprecation of the `@types` package.

**Comment by oprogramador** [comment]
Thanks for this suggestion but I'm not interested in having any TypeScript in this repo.

Generally, you can do whatever you want in a separate repo like creating a fork with TS or creating a new directory in https://github.com/DefinitelyTyped/DefinitelyTyped
